[build]
  command = "python3 -m venv venv && source venv/bin/activate && pip install -r requirements.txt && flask run --host=0.0.0.0 --port=$PORT"
  publish = "app.py"

[dev]
  command = "source venv/bin/activate && flask run --host=0.0.0.0 --port=$PORT"