[build]
  command = "python3 -m venv venv && . venv/bin/activate && pip install -r requirements.txt && flask run --host=0.0.0.0 --port=$PORT"
  publish = "app.py"

[dev]
  command = "python3 -m venv venv && . venv/bin/activate && pip install -r requirements.txt && flask run --host=0.0.0.0 --port=$PORT"